accounts/api/urls.py
from django.urls import include, path
from rest_framework_simplejwt.views import TokenRefreshView

from .custom_claims import MyTokenObtainPairView
from .views import EditEmployeeProfileAPIView, SocialLoginAPIView, registration

urlpatterns = [
    # path('login/', TokenObtainPairView.as_view()),
    path("register/", registration, name="register"),
    path("login/", MyTokenObtainPairView.as_view()),
    path("token/refresh/", TokenRefreshView.as_view()),
    path("employee/", include([path("profile/", EditEmployeeProfileAPIView.as_view(), name="employee-profile")])),
    path("oauth/login/", SocialLoginAPIView.as_view()),
]

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from jobsapp.views import EditProfileView, EmployerProfileEditView

from .views import *

app_name = "accounts"

urlpatterns = [
     path("searchcompany/", SearchcompanyView.as_view(), name="searchcompany"),
    path("employee/register/", RegisterEmployeeView.as_view(), name="employee-register"),
    path("employer/register/", RegisterEmployerView.as_view(), name="employer-register"),
    path("employer/<int:id>/",  JobCompanyView.as_view(), name="employer-company"),
    path("employee/profile/update/", EditProfileView.as_view(), name="employee-profile-update"),
    path("employer/profile/update/", EmployerProfileEditView.as_view(), name="employer-profile-update"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("companysearch/", CompanyListView.as_view(), name="companylist"),
    path("companysearch/<int:id>", Viewalljobs.as_view(), name="viewcompanyjobs"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from contact.views import contact_view

from .views import *

app_name = "contact"

urlpatterns = [
    path("contact/", contact_view.as_view(), name="contact"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import re_path 
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView
from jobs.sitemaps import Sitemaps, StaticViewSitemap
from django.contrib.auth import views as auth_views



schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(path("", include("jobsapp.urls")),
                              path("", include("accounts.urls")),
                              path("", include("contact.urls")),
                              )

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    re_path(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
    path("graphql/", csrf_exempt(FileUploadGraphQLView.as_view(graphiql=True))),
    path('change-password', auth_views.PasswordChangeView.as_view(success_url="/"),name="change-password"),
]

jobsapp/urls.py
from django.urls import include, path
from . import views
from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path("all-applicants/", ApplicantsListView.as_view(), name="employer-all-applicants"),
                path("applicants/<int:job_id>/", ApplicantPerJobView.as_view(), name="employer-dashboard-applicants"),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
                path("delete/<int:job_id>/", views.delete,name="delete"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path("my-applications", EmployeeMyJobsListView.as_view(), name="employee-my-applications"),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
    path('about/', views.about,name="about"),
    # path("companysearch/<int:id>", Viewalljobs.as_view(), name="viewcompanyjobs"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from accounts.managers import UserManager

GENDER_CHOICES = (("male", "Male"), ("female", "Female"))


class User(AbstractUser):
    username = None
    role = models.CharField(max_length=12, error_messages={"required": "Role must be provided"})
    gender = models.CharField(max_length=10, blank=True, null=True, default="")
    email = models.EmailField(
        unique=True, blank=False, error_messages={"unique": "A user with that email already exists."}
    )
    mobileno = models.CharField(max_length=10)
    city = models.CharField( max_length=100)
    qualification = models.CharField(max_length=30)
    resume = models.FileField()
    company_description = models.CharField(max_length=500)

    objects = UserManager()

    class Meta:
        ordering = ["id"]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __unicode__(self):
        return self.email

    

accounts/api/views.py
from django.contrib.auth import get_user_model, login
from requests.exceptions import HTTPError
from rest_framework import decorators, permissions, response, status
from rest_framework.generics import GenericAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken
from social_core.backends.oauth import BaseOAuth2
from social_core.exceptions import AuthForbidden, AuthTokenError, MissingBackend
from social_django.utils import load_backend, load_strategy

from jobsapp.api.permissions import IsEmployee

from .custom_claims import MyTokenObtainPairSerializer
from .serializers import SocialSerializer, UserCreateSerializer, UserSerializer

User = get_user_model()


@decorators.api_view(["POST"])
@decorators.permission_classes([permissions.AllowAny])
def registration(request):
    serializer = UserCreateSerializer(data=request.data)
    if not serializer.is_valid(raise_exception=True):
        return response.Response(serializer.errors, status.HTTP_400_BAD_REQUEST)
    user = serializer.save()
    res = {"status": True, "message": "Successfully registered"}
    return response.Response(res, status.HTTP_201_CREATED)


class EditEmployeeProfileAPIView(RetrieveUpdateAPIView):
    serializer_class = UserSerializer
    http_method_names = ["get", "put"]
    permission_classes = [IsAuthenticated, IsEmployee]

    def get_object(self):
        return self.request.user


class SocialLoginAPIView(GenericAPIView):
    """Log in using facebook"""

    serializer_class = SocialSerializer
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        """Authenticate user through the provider and access_token"""
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        provider = serializer.data.get("provider", None)
        strategy = load_strategy(request)

        try:
            backend = load_backend(strategy=strategy, name=provider, redirect_uri=None)

        except MissingBackend:
            return Response({"error": "Please provide a valid provider"}, status=status.HTTP_400_BAD_REQUEST)
        try:
            if isinstance(backend, BaseOAuth2):
                access_token = serializer.data.get("access_token")
            user = backend.do_auth(access_token)
        except HTTPError as error:
            return Response(
                {"error": {"access_token": "Invalid token", "details": str(error)}}, status=status.HTTP_400_BAD_REQUEST
            )
        except AuthTokenError as error:
            return Response({"error": "Invalid credentials", "details": str(error)}, status=status.HTTP_400_BAD_REQUEST)

        try:
            authenticated_user = backend.do_auth(access_token, user=user)

        except HTTPError as error:
            return Response({"error": "invalid token", "details": str(error)}, status=status.HTTP_400_BAD_REQUEST)

        except AuthForbidden as error:
            return Response({"error": "invalid token", "details": str(error)}, status=status.HTTP_400_BAD_REQUEST)

        if authenticated_user and authenticated_user.is_active:
            # generate JWT token
            login(request, authenticated_user)
            # data = {"token": jwt_encode_handler(jwt_payload_handler(user))}
            # token = RefreshToken.for_user(user)
            token = MyTokenObtainPairSerializer.get_token(user)
            # customized response
            context = {
                "email": authenticated_user.email,
                "username": authenticated_user.username,
                "access": str(token.access_token),
                "refresh": str(token),
            }
            return Response(status=status.HTTP_200_OK, data=context)

accounts/views.py
from pyexpat import model
from django.contrib import auth, messages
from django.http import HttpResponseRedirect,Http404
from django.shortcuts import redirect, render
from django.views.generic import CreateView, FormView, RedirectView,DetailView,ListView
from accounts.forms import *
from accounts.models import User
from jobsapp.models import *



class RegisterEmployeeView(CreateView):
    model = User
    form_class = EmployeeRegistrationForm
    template_name = "accounts/employee/register.html"
    success_url = "/"

    extra_context = {"title": "Register"}

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password1")
            user.set_password(password)
            user.save()
            return redirect("accounts:login")
        else:
            return render(request, "accounts/employee/register.html", {"form": form})


class RegisterEmployerView(CreateView):
    model = User
    form_class = EmployerRegistrationForm
    template_name = "accounts/employer/register.html"
    success_url = "/"

    extra_context = {"title": "Register"}

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password1")
            user.set_password(password)
            user.save()
            return redirect("accounts:login")
        else:
            return render(request, "accounts/employer/register.html", {"form": form})


class LoginView(FormView):
    """
    Provides the ability to login as a user with an email and password
    """

    success_url = "/"
    form_class = UserLoginForm
    template_name = "accounts/login.html"

    extra_context = {"title": "Login"}

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().dispatch(self.request, *args, **kwargs)

    def get_success_url(self):
        if "next" in self.request.GET and self.request.GET["next"] != "":
            return self.request.GET["next"]
        else:
            return self.success_url

    def get_form_class(self):
        return self.form_class

    def form_valid(self, form):
        auth.login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(self.get_context_data(form=form))


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """

    url = "/login"

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        messages.success(request, "You are now logged out")
        return super(LogoutView, self).get(request, *args, **kwargs)


class JobCompanyView(DetailView):
    model = User
    template_name = "accounts/employer/company.html"
    context_object_name = "user"
    pk_url_kwarg = "id"

    def get_object(self, queryset=None):
        obj = super(JobCompanyView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Company doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # raise error
            raise Http404("Company doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class SearchcompanyView(ListView):
    model = User
    template_name = "searchcompany.html"
    context_object_name = "searchcompany"
    

    def get_queryset(self):
        # q = JobDocument.search().query("match", title=self.request.GET['position']).to_queryset()
        # print(q)
        # return q
        return self.model.objects.filter(
            city__contains=self.request.GET.get("city", ""),
            first_name__contains=self.request.GET.get("Name", ""),
        )

class CompanyListView(ListView):
    model = User
    template_name = "companysearch.html"
    context_object_name = "companylist"
    paginate_by = 5

    def get_queryset(self):

     return self.model.objects.filter(
            role='employer'
        )


class Viewalljobs(ListView):
    model =Job
    template_name = "companyjobs.html"
    context_object_name = "viewcompanyjobs"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Job.objects.filter(user_id=self.kwargs["id"]).order_by("id")

   

    # def dispatch(self, request,id, *args, **kwargs):
    #     return super().dispatch(self.request,id, *args, **kwargs)
   
    # def get(self,request, primary_key):
    #  try:
    #     JOB = self.model.objects.get(user_id=primary_key)
    #  except JOB.DoesNotExist:
    #     raise Http404('job does not exist')
    #  return JOB

    # def get_queryset(self):
    #    return self.model.objects.filter(user_id= id)
         
         

templates/accounts/employer/company.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% load humanize %}
{% block title %}
    Company Profile
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading">{{ user.first_name }}<br>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
                {{ user.city }} 

            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h5>Contact: {{ user.email }}</h5>
        
    
                    <blockquote class="blockquote"><b>Company Description</b>
                        <p>{{ user.company_description }}</p>
                    </blockquote>
                   
                </div>
               
                
            </div>
        </div>
    </section>













<!-- 

    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Job title</th>
                                <th>Position filled</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                
                                  
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                  
                </div>
            </div>
        </div>
    </section> -->





{% endblock %}

templates/accounts/employer/register.html
{% extends 'base.html' %}
{% block title %}
    Employer Register
{% endblock %}

{% block content %}

    <div class="col-lg-6 offset-3 mt-3">
        <div class="box">
            <h3 class="heading">Register</h3>
           
            <p class="text-muted">If you have any questions, please feel free to <a href="{% url 'contact:contact' %}">contact us</a>,
                our customer service center is working for you 24/7.</p>
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-user-md"></i> Register
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}