accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from jobsapp.views import EditProfileView, EmployerProfileEditView

from .views import *

app_name = "accounts"

urlpatterns = [
     path("searchcompany/", SearchcompanyView.as_view(), name="searchcompany"),
    path("employee/register/", RegisterEmployeeView.as_view(), name="employee-register"),
    path("employer/register/", RegisterEmployerView.as_view(), name="employer-register"),
    path("employer/<int:id>/",  JobCompanyView.as_view(), name="employer-company"),
    path("employee/profile/update/", EditProfileView.as_view(), name="employee-profile-update"),
    path("employer/profile/update/", EmployerProfileEditView.as_view(), name="employer-profile-update"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("companysearch/", CompanyListView.as_view(), name="companylist"),
    path("companysearch/<int:id>", Viewalljobs.as_view(), name="viewcompanyjobs"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from contact.views import contact_view

from .views import *

app_name = "contact"

urlpatterns = [
    path("contact/", contact_view.as_view(), name="contact"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import re_path 
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView
from jobs.sitemaps import Sitemaps, StaticViewSitemap
from django.contrib.auth import views as auth_views



schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(path("", include("jobsapp.urls")),
                              path("", include("accounts.urls")),
                              path("", include("contact.urls")),
                              )

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    re_path(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
    path("graphql/", csrf_exempt(FileUploadGraphQLView.as_view(graphiql=True))),
    path('change-password', auth_views.PasswordChangeView.as_view(success_url="/"),name="change-password"),
]

jobsapp/urls.py
from django.urls import include, path
from . import views
from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path("all-applicants/", ApplicantsListView.as_view(), name="employer-all-applicants"),
                path("applicants/<int:job_id>/", ApplicantPerJobView.as_view(), name="employer-dashboard-applicants"),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
                path("delete/<int:job_id>/", views.delete,name="delete"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path("my-applications", EmployeeMyJobsListView.as_view(), name="employee-my-applications"),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
    path('about/', views.about,name="about"),
    # path("companysearch/<int:id>", Viewalljobs.as_view(), name="viewcompanyjobs"),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
     
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

contact/forms.py
from django import forms
from .models import Contact
from django.contrib.auth.forms import UserCreationForm


class ContactForm(forms.ModelForm):
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    message = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields["email"].required = "Email"
        self.fields["subject"].label = "Subject"
        self.fields["message"].label = "Message"
       

        self.fields["email"].widget.attrs.update({"placeholder": "Enter Your EmailId"})
        self.fields["subject"].widget.attrs.update({"placeholder": "Enter Subject"})
        self.fields["message"].widget.attrs.update({"placeholder": "Enter Your Message"})

    class Meta:
        model = Contact
        fields = ["email", "subject", "message"]
        error_messages = {
            "email": {"required": "Email is required"},
            "subject": {"required": "Subject is required", "max_length": "Subject is too long"},
            "message": {"required": "Message is required"},
        }  

contact/views.py
from django.shortcuts import render,redirect
from .forms import ContactForm
from django.views.generic import CreateView
from contact.models import Contact



class contact_view(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = "contact.html"
    success_url = "/"

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():
           form.save()
           return render(request, "home.html")
        else:
            return render(request, "contact.html", {"form": form})

jobsapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect, JsonResponse, HttpResponseNotAllowed
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView

from ..decorators import user_is_employee
from ..forms import ApplyJobForm
from ..models import Applicant, Favorite, Job
from django.shortcuts import render

class HomeView(ListView):
    model = Job
    template_name = "home.html"
    context_object_name = "jobs"

    def get_queryset(self):
        return self.model.objects.unfilled()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trendings"] = self.model.objects.unfilled(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
    model = Job
    template_name = "jobs/search.html"
    context_object_name = "jobs"

    def get_queryset(self):
        # q = JobDocument.search().query("match", title=self.request.GET['position']).to_queryset()
        # print(q)
        # return q
        return self.model.objects.filter(
            location__contains=self.request.GET.get("location", ""),
            title__contains=self.request.GET.get("position", ""),
        )


class JobListView(ListView):
    model = Job
    template_name = "jobs/jobs.html"
    context_object_name = "jobs"
    paginate_by = 5


class JobDetailsView(DetailView):
    model = Job
    template_name = "jobs/details.html"
    context_object_name = "job"
    pk_url_kwarg = "id"

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # raise error
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)





class ApplyJobView(CreateView):
    model = Applicant
    form_class = ApplyJobForm
    slug_field = "job_id"
    slug_url_kwarg = "job_id"

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employee)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(self._allowed_methods())

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, "Successfully applied for the job!")
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy("jobs:home"))

    def get_success_url(self):
        return reverse_lazy("jobs:jobs-detail", kwargs={"id": self.kwargs["job_id"]})

    # def get_form_kwargs(self):
    #     kwargs = super(ApplyJobView, self).get_form_kwargs()
    #     print(kwargs)
    #     kwargs['job'] = 1
    #     return kwargs

    def form_valid(self, form):
        # check if user already applied
        applicant = Applicant.objects.filter(user_id=self.request.user.id, job_id=self.kwargs["job_id"])
        if applicant:
            messages.info(self.request, "You already applied for this job")
            return HttpResponseRedirect(self.get_success_url())
        # save applicant
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


def favorite(request):
    if not request.user.is_authenticated:
        return JsonResponse(data={"auth": False, "status": "error"})

    job_id = request.POST.get("job_id")
    user_id = request.user.id
    try:
        fav = Favorite.objects.get(job_id=job_id, user_id=user_id, soft_deleted=False)
        if fav:
            fav.soft_deleted = True
            fav.save()
            return JsonResponse(
                data={"auth": True, "status": "removed", "message": "Job removed from your favorite list"}
            )
    except Favorite.DoesNotExist:
        Favorite.objects.create(job_id=job_id, user_id=user_id)
        return JsonResponse(data={"auth": True, "status": "added", "message": "Job added to your favorite list"})

def about(request):
    return render(request,"about.html")


# class Viewalljobs(ListView):
#     model = Job
#     template_name = "companyjobs.html"
#     context_object_name = "viewcompanyjobs"
    # pk_url_kwarg = "id"


    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(self.request, *args, **kwargs)

    # def get_queryset(self):
    #    return self.model.objects.filter(user_id=self.request.user.id)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    About Us
{% endblock %}

{% block content %}
<section class="about-form-section about-form-section--image overlay">
 <div class="container">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="about-form-box">
              <div class="container mt-5 mb-5">
                <h2 class="heading">ABOUT US</h2>
                <h5><a>We are here to provide you with easier and faster way to look for a job and apply it at convenience of your home.You can easily connect with your dream job and company.We also provide you vast number of companies which you can explore easily from anywhere.</a></h5>
              </div>
            </div>
       </div>
    </div>
 </div>

</section>
{% endblock %}

templates/companysearch.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load is_favorited %}
{% block title %}
    Search Companies
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">COMPANIES</h4>
            <form id="job-main-form" method="get" action="{% url 'accounts:searchcompany' %}" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-center">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="name">{% trans 'Name' %}</label>
                                <input type="text" id="name" name="Name"
                                       placeholder="Company Name" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="city">City</label>
                                <input type="text" id="city" name="city"
                                       placeholder="Any particular city?" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button type="submit"
                                    class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">Find your favorite company</h3>
            {% for users in companylist %}
                {% if users.role == 'employer' %}
           
                    <div class="job-listing ">
                       <div class="row">
                           <div class="col-md-12 col-lg-6">
                              <div class="row">
                                 <div class="col-2">
                                     <img src="{% static 'img/jp.png' %}"
                                        alt="Ipsioou " class="img-fluid">
                                 </div>
                                 <div class="col-10">
                                     <h4 class="job__title"><a
                                        href="{% url 'accounts:employer-company' users.id %}">{{ users.first_name }}</a></h4>                            
                                 </div>
                                </div>
                             </div>
                           <div class="col-10 col-md-3  ml-auto"><i class="fa fa-map-marker job__location"></i>
                             {{ users.city }}
                            </div>

                            <div class="col-sm-12 col-md-2  ml-auto"><a class="btn btn-outline-white-primary" href="{% url 'accounts:viewcompanyjobs' users.id %}">Posted jobs</a>  
                            </div>
                        </div>   
                    </div>
                     
                {% endif %}
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--image overlay ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job-form-box">
                        <h2 class="heading">Find a <span class="accent">job</span> you will
                            <span class="accent">love</span>.
                        </h2>
                        <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="job-main-form">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">{% trans 'Position' %}</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Featured jobs</h3>
            <div class="row featured align-items-stretch">
                {% for job in jobs %}
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="box-image-text bg-visible full-height">
                            <div class="top">
                                <a href="#">
                                    <div class="image">
                                        <img src="{% static 'img/jp.png' %}" alt="" class="img-fluid">
                                    </div>
                                    <div class="bg"></div>
                                    
                                </a>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h5>
                                <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                    {{ job.location }}
                                    {% if job.type == '1' %}
                                        <span class="badge featured-badge badge-success">Full time</span>
                                    {% elif job.type == '2' %}
                                        <span class="badge featured-badge badge-primary">Part time</span>
                                    {% else %}
                                        <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                    {% endif %}
                                </p>
                                {% for tag in job.tags.all %}
                                    <span style="color: #ffffff;"
                                          class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                                {% endfor %}
                               
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h4 class="heading">Trending this month</h4>
            {% for trending in trendings %}
                <div class="job-listing  job-listing--last">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="ShareBoardd " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title">
                                        <a href="{% url 'jobs:jobs-detail' trending.id %}">{{ trending.title }}</a>
                                    </h4>
                                    <p class="job__company">
                                        {{ trending.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ trending.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ trending.created_at|timesince }}</p>
                        </div>
                        <div class="col-sm-12 col-md-2 col-lg-1">
                            <div class="job__star">
                                <a href="#" data-toggle="tooltip" data-placement="top"
                                   title="Save to favourites" class="job__star__link">
                                    <i class="fa fa-star"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <section class="section-divider">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Start searching for your new job now! </p>
                    <p><a href="{% url 'jobs:jobs' %}" class="btn btn-outline-light">See our job offers </a></p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/searchcompany.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Search Companies
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find a <span class="accent">Company </span> you will <span class="accent">love</span></h4>
            <form id="job-main-form" method="get" action="#" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Name</label>
                            <input type="text" id="name" name="Name"
                                   placeholder="Name of Company you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">City</label>
                            <input type="text" id="city" name="city" placeholder="Any particular city?"
                                   value="" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">Find your favorite company</h3>
            {% for users in searchcompany %}
            {% if users.role == 'employer' %}
           
            <div class="job-listing  ">
                <div class="row">
                    <div class="col-md-12 col-lg-6">
                        <div class="row">
                            <div class="col-2">
                                <img src="{% static 'img/jp.png' %}"
                                     alt="Ipsioou " class="img-fluid">
                            </div>
                            <div class="col-10">
                                <h4 class="job__title"><a
                                        href="{% url 'accounts:employer-company' users.id %}">{{ users.first_name }}</a></h4>
                               
                            
                            </div>
                        </div>
                    </div>
                    <div class="col-10 col-md-3  ml-auto"><i class="fa fa-map-marker job__location"></i>
                        {{ users.city }}
                    </div>
                    
                
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}